export type CharacterControllerComponentDataType = {
  moveSpeed?: number; // Movement speed in units per second (default: 5.0)
  jumpForce?: number; // Jump initial velocity (default: 8.0)
  jumpHoldForce?: number; // Additional force while holding jump button (default: 20.0 m/s²)
  jumpCutVelocity?: number; // Max vertical velocity when jump is cut (default: -2.0, negative = falls)
  accelerationFactor?: number; // Time to reach max speed in seconds (default: 0.5)
  decelerationFactor?: number; // Time to stop completely in seconds (default: 0.5)
  coyoteTime?: number; // Grace period to jump after leaving ground in seconds (default: 0.15)
  airControlMultiplier?: number; // Air control strength (0.0 = no control, 1.0 = full control, default: 0.3)
  slideSpeedThreshold?: number; // Minimum speed to activate slide (default: 3.0)
  slideDecelerationTime?: number; // Slide duration in seconds (default: 1.5)
  slideHeightMultiplier?: number; // Height reduction during slide (0.5 = half height, default: 0.5)
  slideMinDuration?: number; // Minimum slide duration before it can be cancelled in seconds (default: 0.5)
  wallJumpForce?: number; // Wall jump vertical force (default: 8.0)
  wallJumpAwayForce?: number; // Wall jump horizontal push away from wall (default: 6.0)
  wallCheckDistance?: number; // Distance to check for walls (default: 0.6)
  wallSlideGravityMultiplier?: number; // Gravity reduction when sliding on wall (default: 0.3)
  wallJumpCooldown?: number; // Cooldown between wall jumps in seconds (default: 0.5)
};
