export type CharacterControllerComponentDataType = {
  moveSpeed?: number; // Movement speed in units per second (default: 5.0)
  jumpForce?: number; // Jump force/initial velocity (default: 8.0)
  accelerationTime?: number; // Time to reach max speed in seconds (default: 0.5)
  decelerationTime?: number; // Time to stop completely in seconds (default: 0.5)
  coyoteTime?: number; // Grace period to jump after leaving ground in seconds (default: 0.15)
  airControlMultiplier?: number; // Air control strength (0.0 = no control, 1.0 = full control, default: 0.3)
  slideSpeedThreshold?: number; // Minimum speed to activate slide (default: 3.0)
  slideDecelerationTime?: number; // Slide duration in seconds (default: 1.5)
  slideHeightMultiplier?: number; // Height reduction during slide (0.5 = half height, default: 0.5)
  wallJumpForce?: number; // Wall jump vertical force (default: 8.0)
  wallJumpAwayForce?: number; // Wall jump horizontal push away from wall (default: 6.0)
  wallJumpCooldown?: number; // Cooldown between wall jumps in seconds (default: 0.3)
  wallCheckDistance?: number; // Distance to check for walls (default: 0.6)
  wallSlideGravityMultiplier?: number; // Gravity reduction when sliding on wall (default: 0.3)
};
