export enum PipelineBindGroupLayouts {
  CAMERA_UNIFORMS = 'CameraUniforms',
  OBJECT_UNIFORMS = 'ObjectUniforms',
  MATERIAL_TEXTURES = 'MaterialTextures',
  SINGLE_TEXTURE = 'SingleTexture',
  CUBEMAP_TEXTURE = 'CubemapTexture',
  AMBIENT_UNIFORMS = 'AmbientUniforms',
  SKYBOX_UNIFORMS = 'SkyboxUniforms',
  GBUFFER_UNIFORMS = 'GBufferUniforms',
  BUFFER_UNIFORM = 'BufferUniform',
  DEPTH_TEXTURE = 'DepthTexture',
  FOUR_TEXTURE = 'FourTexture',
  AO_UNIFORMS = 'AmbientOcclusionUniforms',
  DIRECTIONAL_LIGHT_UNIFORMS = 'DirectionalLightUniforms',
  SSR_UNIFORMS = 'SSRUniforms',
}
