export enum PipelineBindGroupLayouts {
  CAMERA_UNIFORMS = 'CameraUniforms',
  OBJECT_UNIFORMS = 'ObjectUniforms',
  MATERIAL_TEXTURES = 'MaterialTextures',
  SINGLE_TEXTURE = 'SingleTexture',
  CUBEMAP_TEXTURE = 'CubemapTexture',
  AMBIENT_UNIFORMS = 'AmbientUniforms',
  SKYBOX_UNIFORMS = 'SkyboxUniforms',
  GBUFFER_UNIFORMS = 'GBufferUniforms',
  BUFFER_UNIFORM = 'BufferUniform',
  DEPTH_TEXTURE = 'DepthTexture',
  FOUR_TEXTURE = 'FourTexture',
  AO_UNIFORMS = 'AmbientOcclusionUniforms',
  DIRECTIONAL_LIGHT_UNIFORMS = 'DirectionalLightUniforms',
  SSR_UNIFORMS = 'SSRUniforms',
  SSR_COMPOSE_UNIFORMS = 'SSRComposeUniforms',
  TEMPORAL_ACCUMULATION_UNIFORMS = 'TemporalAccumulationUniforms',
  FROXEL_UNIFORMS = 'FroxelUniforms',
  PARTICLE_UNIFORMS = 'ParticleUniforms',
  INSTANCE_STORAGE = 'InstanceStorage',
  DOF_PARAMS = 'DOFParams',
  DOF_BLUR_TEXTURES = 'DOFBlurTextures',
  DOF_COMPOSITE_TEXTURES = 'DOFCompositeTextures',
  MOTION_BLUR_PARAMS = 'MotionBlurParams',
  SMAA_PARAMS = 'SMAAParams',
  SMAA_BLEND_TEXTURES = 'SMAABlendTextures',
}
